### ISSUE TITLE
return values ? values.split(',') : []

### ISSUE THREAD

**Issue by eephyne** [thumbsup/thumbsup#83]
```
Thumbsup version: 2.2.0-alpha.3
Node version: 9.2.0
NPM version: 5.5.1
Operating system: arch linux
```
I did'nt tested my main folder after upgrading for resolve empty file bug, but when I do so I got this
```
http@playbox  % DEBUG="*" node_modules/.bin/thumbsup --input /-----/photos/ --output ./thumbsup

 ⠙ Indexing folder
   Resizing media
   Creating website
  snapdragon:compiler initializing /-/snapdragon/lib/compiler.js +0ms
  snapdragon:parser initializing /-/snapdragon/lib/parser.js +7ms
  snapdragon:compiler initializing /-/snapdragon/lib/compiler.js +18ms
  snapdragon:parser initializing /-/snapdragon/lib/parser.js +1ms
  snapdragon:compiler initializing /-/snapdragon/lib/compiler.js +6ms
  snapdragon:parser initializing /-/snapdragon/lib/parser.js +1ms
  snapdragon:compiler initializing /-/snapdragon/lib/compiler.js +6ms
  snapdragon:parser initializing /-/snapdragon/lib/parser.js +1ms
  snapdragon:compiler initializing /-/snapdragon/lib/compile ⠼ Indexing folder
   Resizing media
   Creating website
/-/thumbsup/src/model/metadata.js:72
  return values ? values.split(',') : []
                         ^

TypeError: values.split is not a function
    at keywords (/-/thumbsup/src/model/metadata.js:72:26)
    at new Metadata (/-/thumbsup/src/model/metadata.js:28:21)
    at EventEmitter.emitter.on.file (/-/thumbsup/src/steps/step-index.js:33:20)
    at EventEmitter.emit (events.js:159:13)
    at finished (/-/thumbsup/src/components/index/index.js:44:17)
    at globber.find (/-/thumbsup/src/components/index/index.js:78:16)
    at Readable.stream.on (/-/thumbsup/src/components/index/glob.js:22:26)
    at Readable.emit (events.js:159:13)
    at endReadableNT (_stream_readable.js:1054:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)

```

**Comment by eephyne** [comment]
it seem to be related to the old thumbsdb. I delete it, recontruct it and report here if that make any change.

**Comment by rprieto** [comment]
Thanks for the report. That's related to the keyword processing. Quick questions:
- is there a `picasa.ini` in any of the folders?
- what's the version of `exiftool` on your system?

**Comment by eephyne** [comment]
no picasa.ini in any folders and exiftool is ver 10.55.

I rebuild the db and same result

**Comment by eephyne** [comment]
like I already said I'm not familiar with node but values typeof return Object, thus its kind of normal to get this error no ?

I replaced 
`    return values ? values.split(',') : []`

with 
`    return values ? JSON.stringify(values).split(',') : []`

it seem to work but I really don't know if this is a good idea

**Comment by rprieto** [comment]
The `keywords` IPTC section of a photo should be a string in the `word1,word2,word3` format. I wonder if your photo is different.

Can you please add the following code around line 72, to see which file has the issue?

```js
function keywords (exif, picasa) {
  const values = picasaValue(picasa, 'keywords') ||
                 tagValue(exif, 'IPTC', 'Keywords')
  // ---------------------------------
  if (typeof values !== 'string') {
    console.log('path', exif.SourceFile)
    console.log('keywords', values)
  }
  // ---------------------------------
  return values ? values.split(',') : []
}
```

And then running:

```
exiftool -a -s -g -struct -json PATH_TO_THE_PHOTO | grep Keywords
```

**Comment by eephyne** [comment]
I got this `    "Keywords": ["rats","pupuce"]`

**Comment by rprieto** [comment]
Thanks for that. Reading through the `exiftool` docs again I think I misunderstood how keywords are returned. Looks like it's a string if there's only 1 and an array if there's several. I'll add new tests & a fix!

**Comment by rprieto** [comment]
A fix is available on the `iptc-keywords` branch. It will be part of the next release, let me know if you try it before that!

**Comment by eephyne** [comment]
its working
But I still have the bug of generating again the thumb even if they're all already done but thats another issue :)

nice work

**Comment by rprieto** [comment]
Glad it's working. A few more bugs to fix and v2.2.0 should be out soon! Thanks again for all your help. Don't hesitate to raise an issue for the thumbnail problem, it should already re-build them if the source photo date > thumbnail date.
